# Generated by Django 5.2 on 2025-05-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlavni', '0003_repairreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spz', models.CharField(max_length=10)),
                ('znacka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('prevodovka', models.CharField(choices=[('manual', 'Manuální'), ('automat', 'Automatická')], max_length=20)),
                ('dostupnost', models.BooleanField(default=True)),
            ],
        ),
    ]
